//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental_Lab.Model
{
    using System;using System.ComponentModel;using PropertyChanged;
    using System.Collections.Generic;
    
    public partial class Appointment : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        public int Id { get; set; }
        public string Subject { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User Doctor { get; set; }
    }
}
