//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dental_Lab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string Code { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
